# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Encode-EUCJPASCII
version:      0.01
version_from: EUCJPASCII.pm
requires:
    Encode:                        1.41

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
